version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tesla-service-3d
    restart: always
    ports:
      - "1905:3000"
    environment:
      - NODE_ENV=production