version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tesla-service-3d
    restart: always
    ports:
      - "1905:1905"
    environment:
      - NODE_ENV=production
      - PORT=1905
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:1905"]
      interval: 10s
      timeout: 5s
      retries: 3 